core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', Home.as_view(), name='Home'),
    path('', include('empresa.urls', namespace='empresa'))
]

core/empresa/urls.py
from django.urls import path
from .views import AceptarInvitacion, CreateContactoEmpresa, CreateEmpresa, CreateEmpresaCliente, CreateInvitaciones, DeleteContactoEmpresa, DeleteEmpresa, DeleteEmpresaCliente, DeleteUsuarioInvitado, ListContactoEmpresa, ListEmpresa, ListEmpresaCliente, ListInvitaciones, ListUsuarios, RechazarInvitacion, UpdateContactoEmpresa, UpdateEmpresa, UpdateEmpresaCliente, json_load
app_name = "empresa"

urlpatterns = [
    #path('upload/city-country', json_load, name="city-country"),
    #empresa
    path('create/empresa', CreateEmpresa, name="create-empresa"),
    path('list/empresa', ListEmpresa.as_view(), name="list-empresa"),
    path('update/empresa/<pk>', UpdateEmpresa.as_view(), name="update-empresa"),
    path('delete/empresa/<pk>', DeleteEmpresa.as_view(), name="delete-empresa"),
    #usuarios e invitaciones
    path('list/usuarios/', ListUsuarios.as_view(), name="list-usuario"),
    path('invitar/usuario/<user>', CreateInvitaciones.as_view(), name="invitar-usuario"),
    path('list/invitaciones', ListInvitaciones.as_view(), name="list-invitaciones"),
    path('aceptar/invitaciones/<user>', AceptarInvitacion.as_view(), name="aceptar-invitaciones"),
    path('rechazar/invitaciones/<user>', RechazarInvitacion.as_view(), name="rechazar-invitaciones"),
    path('delete/usuario_invitado/<user>', DeleteUsuarioInvitado.as_view(), name="delete-usuario-invitado"),
    #empresa cliente
    path('create/empresa_cliente/', CreateEmpresaCliente, name="create-empresa-cliente"),
    path('listar/empresa_cliente/', ListEmpresaCliente.as_view(), name="list-empresa-cliente"),
    path('delete/empresa_cliente/<pk>', DeleteEmpresaCliente.as_view(), name="delete-empresa-cliente"),
    path('update/empresa_cliente/<pk>', UpdateEmpresaCliente.as_view(), name="update-empresa-cliente"),

    #contactos empresa cliente
    path('create/empresa_cliente/contactos/<pk>', CreateContactoEmpresa.as_view(), name ="create-contacto-cliente"),
    path('Delte/empresa_cliente/contactos/<pk>', DeleteContactoEmpresa.as_view(), name ="delete-contacto-cliente"),
    path('listar/empresa_cliente/contactos/<pk>', ListContactoEmpresa.as_view(), name="list-contacto-cliente"),
    path('update/empresa_cliente/contactos/<pk>', UpdateContactoEmpresa.as_view(), name="update-contacto-cliente"),
]

core/core/views.py
from django.views.generic import TemplateView

class Home(TemplateView):
    template_name = 'core/home.html'

core/templates/core/base.html
<html>
{% include 'core/head.html' %}
<body id="page-top">
    <div id="wrapper">
        {% include 'core/nav.html' %}
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <footer class="bg-white sticky-footer">
            <div class="container my-auto">
                <div class="text-center my-auto copyright"><span>Copyright © Brand 2021</span></div>
            </div>
        </footer>
    </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a></div>
    
</body>
{% include 'core/script.html' %}
</html>

core/templates/core/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Blank Page - Brand</title>
    <link rel="stylesheet" href="{% static 'core/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <script src="https://kit.fontawesome.com/321be02fdc.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'core/fonts/simple-line-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/Elegant-Registration-Form.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/FORM.css' %}">
</head>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% include 'core/nav.html' %}
{% block content %}
<div class="card shadow">
    <div class="card-header py-3">
        {% comment %} <p class="text-primary m-0 font-weight-bold">Home :3</p> {% endcomment %}
    </div>
    <div class="card-body">

    </div>
</div>
{% endblock content %}

core/templates/core/nav.html
<nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
    <div class="container-fluid d-flex flex-column p-0">
        <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                <div class="sidebar-brand-icon rotate-n-15"><i class="fas fa-project-diagram"></i></div>
                <div class="sidebar-brand-text mx-3"><span>TEST</span></div>
        </a>
        <hr class="sidebar-divider my-0">
        <ul class="nav navbar-nav text-light" id="accordionSidebar">
        {% comment %} {% if request.user.groups.id == 3 %} {% endcomment %}
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="{% url 'empresa:create-empresa' %}">
                    <i class="fas fa-plus"></i>
                    <span>Crear Empresa</span>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="{% url 'empresa:create-empresa-cliente' %}">
                    <i class="fas fa-plus"></i>
                    <span>Crear Empresa Cliente</span>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="{% url 'empresa:list-empresa' %}">
                    <i class="fas fa-folder-plus"></i>
                    <span>Ver Empresa</span>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="{% url 'empresa:list-empresa-cliente' %}">
                    <i class="fas fa-folder-plus"></i>
                    <span>Ver Empresa Cliente</span>
                </a>
            </li>
            {% comment %} {% endif %} {% endcomment %}
            {% if not request.user.is_authenticated %}
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="{% url 'account_login' %}">
                    <i class="fas fa-user"></i>
                    <span>Login</span>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="{% url 'account_signup' %}">
                    <i class="fas fa-user"></i>
                    <span>Registro</span>
                </a>
            </li>
            {% endif %}

            {% if request.user.is_authenticated %}
            {% comment %} {% if not request.user.groups.id == 1 %} {% endcomment %}
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="{% url 'empresa:list-usuario' %}">
                    <i class="fas fa-eye"></i>
                    <span>Invitar Usuarios</span>
                </a>
            </li>
            {% comment %} {% endif %} {% endcomment %}

            <li class="nav-item" role="presentation">
                <a class="nav-link" href="{% url 'empresa:list-invitaciones' %}">
                    <i class="fas fa-project-diagram"></i>
                    <span>Mis Invitaciones</span>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" href="{% url 'account_logout' %}">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    <span>Salir</span>
                </a>
            </li>
            {% endif %}
        </ul>
        <div class="text-center d-none d-md-inline">
            <button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button>
        </div>
    </div>
</nav>
<div class="d-flex flex-column" id="content-wrapper">
    <div id="content">
        <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
            <div class="container-fluid">
                <ul class="nav navbar-nav flex-nowrap ml-auto">
                    <li class="nav-item dropdown no-arrow" role="presentation">
                        {% if request.user.is_authenticated %}
                        <div class="nav-item dropdown no-arrow">
                            <a
                                class="dropdown-toggle nav-link"
                                data-toggle="dropdown"
                                aria-expanded="false"
                                href="#"
                            >
                                <span class="d-none d-lg-inline mr-2 text-gray-600 small">{{request.user.username}}</span>
                            </a>

                        </div>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>