core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', Home.as_view(), name='Home'),
    path('', include('empresa.urls', namespace='empresa'))
]

core/empresa/urls.py
from django.urls import path
from .views import AceptarInvitacion, CreateContactoEmpresa, CreateEmpresa, CreateEmpresaCliente, CreateInvitaciones, DeleteContactoEmpresa, DeleteEmpresa, DeleteEmpresaCliente, DeleteUsuarioInvitado, ListContactoEmpresa, ListEmpresa, ListEmpresaCliente, ListInvitaciones, ListUsuarios, RechazarInvitacion, UpdateContactoEmpresa, UpdateEmpresa, UpdateEmpresaCliente, json_load
app_name = "empresa"

urlpatterns = [
    #path('upload/city-country', json_load, name="city-country"),
    #empresa
    path('create/empresa', CreateEmpresa, name="create-empresa"),
    path('list/empresa', ListEmpresa.as_view(), name="list-empresa"),
    path('update/empresa/<pk>', UpdateEmpresa.as_view(), name="update-empresa"),
    path('delete/empresa/<pk>', DeleteEmpresa.as_view(), name="delete-empresa"),
    #usuarios e invitaciones
    path('list/usuarios/', ListUsuarios.as_view(), name="list-usuario"),
    path('invitar/usuario/<user>', CreateInvitaciones.as_view(), name="invitar-usuario"),
    path('list/invitaciones', ListInvitaciones.as_view(), name="list-invitaciones"),
    path('aceptar/invitaciones/<user>', AceptarInvitacion.as_view(), name="aceptar-invitaciones"),
    path('rechazar/invitaciones/<user>', RechazarInvitacion.as_view(), name="rechazar-invitaciones"),
    path('delete/usuario_invitado/<user>', DeleteUsuarioInvitado.as_view(), name="delete-usuario-invitado"),
    #empresa cliente
    path('create/empresa_cliente/', CreateEmpresaCliente, name="create-empresa-cliente"),
    path('listar/empresa_cliente/', ListEmpresaCliente.as_view(), name="list-empresa-cliente"),
    path('delete/empresa_cliente/<pk>', DeleteEmpresaCliente.as_view(), name="delete-empresa-cliente"),
    path('update/empresa_cliente/<pk>', UpdateEmpresaCliente.as_view(), name="update-empresa-cliente"),

    #contactos empresa cliente
    path('create/empresa_cliente/contactos/<pk>', CreateContactoEmpresa.as_view(), name ="create-contacto-cliente"),
    path('Delte/empresa_cliente/contactos/<pk>', DeleteContactoEmpresa.as_view(), name ="delete-contacto-cliente"),
    path('listar/empresa_cliente/contactos/<pk>', ListContactoEmpresa.as_view(), name="list-contacto-cliente"),
    path('update/empresa_cliente/contactos/<pk>', UpdateContactoEmpresa.as_view(), name="update-contacto-cliente"),
]

core/empresa/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


class PaisEstadoCiudad(models.Model):
    nombre = models.CharField(verbose_name="Pais, Estado y Ciudad", max_length=150)

    class Meta:
        verbose_name = 'Pais, Estado y Ciudad'
        verbose_name_plural = 'Pises, Estados y Ciudades'
        
    def __str__(self):
        return self.nombre

class Empresa(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Propietario de la empresa")
    nit = models.CharField(max_length=13, verbose_name="Nit")
    nombre = models.CharField(max_length=250, verbose_name="Nombre de la Empresa")
    nombre_comercial = models.CharField(max_length=250, verbose_name="Nombre Comercial")
    direccion = models.CharField(max_length=250, verbose_name="Direccion")
    telefono = PhoneNumberField(unique = True, null = False, blank = False)
    email = models.EmailField(max_length=250, verbose_name="Correo electronico")
    web = models.CharField(max_length=250, verbose_name="Sito Web", unique=True)
    paisestadociudad = models.ForeignKey(PaisEstadoCiudad, on_delete=models.SET_NULL, null=True, verbose_name="Pais, Estado, Ciudad")
    usuarios = models.ManyToManyField(User, verbose_name="Usuarios de la empresa", related_name="usuarios")

    def __str__(self):
        return self.nombre

ESTADO = (
    ('Espera','Espera'),
    ('Aceptada','Aceptada')
)


class Invitaciones(models.Model):
    user = models.ForeignKey(User, verbose_name=("Usuario Invitado"), on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa, verbose_name=("Empresa"), on_delete=models.CASCADE, null=True, blank=True)
    estado = models.CharField(max_length=10, choices=ESTADO, default='Espera')

    def __str__(self):
        return self.user.username


class EmpresaCliente(models.Model):
    nit = models.CharField(max_length=13, verbose_name="Nit")
    nombre = models.CharField(max_length=250, verbose_name="Nombre de la Empresa")
    nombre_comercial = models.CharField(max_length=250, verbose_name="Nombre Comercial")
    direccion = models.CharField(max_length=250, verbose_name="Direccion")
    telefono = PhoneNumberField(unique = True, null = False, blank = False)
    email = models.EmailField(max_length=250, verbose_name="Correo electronico")
    web = models.CharField(max_length=250, verbose_name="Sito Web", unique=True)
    paisestadociudad = models.ForeignKey(PaisEstadoCiudad, on_delete=models.SET_NULL, null=True, verbose_name="Pais, Estado, Ciudad")
    contacto = models.ManyToManyField("ContanctosEmpresa", verbose_name=("Contactos de la empresa"))



class ContanctosEmpresa(models.Model):
    nombre = models.CharField(verbose_name="Nombres", max_length=150)
    apellido = models.CharField(verbose_name="Apellidos", max_length=150)
    email = models.EmailField(max_length=250, verbose_name="Correo electronico")
    telefono =  models.CharField(unique = True, verbose_name="Telefono Fijo",  max_length=150)
    celular = PhoneNumberField(unique = True, null = False, blank = False)
    empresa = models.ForeignKey(EmpresaCliente, verbose_name=("Empresa de la que son contacto "), on_delete=models.CASCADE, null=True)

core/empresa/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls.base import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView
import requests
from empresa.forms import ContanctosEmpresaForm, EmpresaClienteForm, EmpresaForm
from empresa.models import ContanctosEmpresa, Empresa, EmpresaCliente, Invitaciones, PaisEstadoCiudad
from django.views.generic import ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Cargar Pais, Estados y Ciudades
def json_load(request):
    data = requests.get('https://pkgstore.datahub.io/core/world-cities/world-cities_json/data/5b3dd46ad10990bca47b04b4739a02ba/world-cities_json.json')
    my_dict = data.json()  
    data = [] 
    for i in range(0, len(my_dict)):
        if my_dict[i]['country'] != None and my_dict[i]['subcountry'] != None:
            if my_dict[i]['country']+", "+my_dict[i]['subcountry'] not in data:
                data.append(my_dict[i]['country']+", "+my_dict[i]['subcountry'])
                PaisEstadoCiudad.objects.create(nombre = my_dict[i]['country']+", "+my_dict[i]['subcountry']+ ", "+my_dict[i]['name'])
        else:
            if my_dict[i]['country']+", "+my_dict[i]['name'] not in data:
                data.append(my_dict[i]['country']+", "+ my_dict[i]['name'])
                PaisEstadoCiudad.objects.create(nombre = my_dict[i]['country']+", "+ my_dict[i]['name'])        
    return redirect('home')

"""  CRUD CREACION DE LA EMPRESA (PROPIETARIA)  """

#Crear Empresa
@login_required
def CreateEmpresa(request):
    if request.method == 'POST':
        form = EmpresaForm(request.POST) 
        if form.is_valid():
            #si el formulario es valido añadirle el usuario que creo la empresa
            empresa = form.save(commit=False)
            datapais = form.cleaned_data.get('paisestadociudad')
            empresa.paisestadociudad = PaisEstadoCiudad.objects.get(nombre = datapais)
            empresa.user = request.user
            empresa.save()
            return HttpResponseRedirect(reverse('empresa:list-empresa'))

    else:
        form = EmpresaForm()
    context = {
        'form':form,
        'PaisData': PaisEstadoCiudad.objects.all(),
    }

    return render(request, 'empresa/create_empresa.html', context)

#Listar Empresa
class ListEmpresa(LoginRequiredMixin, ListView):
    model = Empresa
    template_name = "empresa/list_empresa.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["object"] = Empresa.objects.filter(user=self.request.user) 
        
        return context

#Editar Empresa
class UpdateEmpresa(LoginRequiredMixin, UpdateView):
    model = Empresa
    form_class = EmpresaForm
    template_name = "empresa/update_empresa.html"
    success_url = reverse_lazy("empresa:list-empresa")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["PaisData"] = PaisEstadoCiudad.objects.all() 
        return context
    
    def form_valid(self, form):
        empresa = form.save()
        datapais = form.cleaned_data.get('paisestadociudad')
        empresa.paisestadociudad = PaisEstadoCiudad.objects.get(nombre = datapais)
        empresa.save()
        return super().form_valid(form)

    #Verificamos si el usuario que quiere editar este objeto es al mismo al que le pertenece
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            empresa = Empresa.objects.get(pk = kwargs['pk'])
            if empresa.user == request.user:
                return super().dispatch(request, *args, **kwargs)
        return redirect('Home')

#Eliminar Empresa
class DeleteEmpresa(LoginRequiredMixin, DeleteView):
    model= Empresa
    template_name = "empresa/delete_empresa.html"
    success_url = reverse_lazy("empresa:list-empresa")

    #Verificamos si el usuario que quiere Eliminar este objeto es al mismo al que le pertenece
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            empresa = Empresa.objects.get(pk = kwargs['pk'])
            if empresa.user == request.user:
                return super().dispatch(request, *args, **kwargs)
        return redirect('Home')

#Listar Los usuarios
class ListUsuarios(LoginRequiredMixin, ListView):
    model = Invitaciones
    template_name = 'empresa/list_usuarios.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            empresa = Empresa.objects.get(user = self.request.user)
        except:
            empresa = None
        context["empresa"] =  empresa
        return context


"""  CRUD DE INVITACIONES A LA EMPRESA (PROPIETARIA)  """
#Crear invitaciones
class CreateInvitaciones(LoginRequiredMixin, DetailView):
    model = Invitaciones

    def get(self, request, *args, **kwargs):
        empresa = Empresa.objects.filter(user = request.user).first()
        invitado = User.objects.get(username = kwargs['user'])

        invitacion = Invitaciones.objects.get(user = invitado)
        invitacion.empresa = empresa
        invitacion.save()
        return redirect('empresa:list-usuario') 

#Listar las invitaciones que tiene de alguna empresa
class ListInvitaciones(LoginRequiredMixin, ListView):
    model = Invitaciones
    template_name = "empresa/list_invitaciones.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["invitaciones"] =  Invitaciones.objects.filter(user = self.request.user)
        return context

#Aceptar invitaciones de las empresas
class AceptarInvitacion(LoginRequiredMixin, DetailView):
    model = Invitaciones

    def get(self, request, *args, **kwargs):
        #actualizacion del estado de la invitacion
        invitado = User.objects.get(username = kwargs['user'])
        invitacion = Invitaciones.objects.get(user = invitado)
        invitacion.estado = "Aceptada"
        invitacion.save()
        #agregando el usuario a la empresa
        empresa = Empresa.objects.get(nombre = invitacion.empresa)
        empresa.usuarios.add(invitado)
        empresa.save()
        return redirect('empresa:list-empresa') 

#Rechazar Invitaciones de las empresas
class RechazarInvitacion(LoginRequiredMixin, DetailView):
    model = Invitaciones

    def get(self, request, *args, **kwargs):
        #actualizacion del estado de la invitacion
        invitado = User.objects.get(username = kwargs['user'])
        invitacion = Invitaciones.objects.get(user = invitado)
        invitacion.estado = "Espera"
        invitacion.empresa = None
        invitacion.save()
        return redirect('empresa:list-empresa')

#Eliminar usuarios invitados a la empresa
class DeleteUsuarioInvitado(LoginRequiredMixin, DetailView):
    model = Empresa 

    def get(self, request, *args, **kwargs):
        invitado = User.objects.get(username = kwargs['user'])
        #agregando el usuario a la empresa
        empresa = Empresa.objects.get(user = self.request.user)
        empresa.usuarios.remove(invitado)

        return redirect('empresa:list-empresa') 


""" CRUD DE LA EMPRESA CLIETNE  """

#Creacion de la Empresa Cliente
def CreateEmpresaCliente(request):
    if request.method == 'POST':
        form = EmpresaClienteForm(request.POST) 
        if form.is_valid():
            #si el formulario es valido añadirle el usuario que creo la empresa
            empresa = form.save(commit=False)
            datapais = form.cleaned_data.get('paisestadociudad')
            empresa.paisestadociudad = PaisEstadoCiudad.objects.get(nombre = datapais)
            empresa.save()
            return HttpResponseRedirect(reverse('empresa:list-empresa'))

    else:
        form = EmpresaClienteForm()
    context = {
        'form':form,
        'PaisData': PaisEstadoCiudad.objects.all(),
    }

    return render(request, 'empresa/create_empresa_cliente.html', context)

#Listar Empresa Cliente
class ListEmpresaCliente(LoginRequiredMixin, ListView):
    model = EmpresaCliente
    template_name = "empresa/list_empresa_cliente.html"

#Eliminar Empresa Cliente
class DeleteEmpresaCliente(LoginRequiredMixin, DeleteView):
    model= EmpresaCliente
    template_name = "empresa/delete_empresa_cliente.html"
    success_url = reverse_lazy("empresa:list-empresa-cliente")

#Editar Empresa Cliente
class UpdateEmpresaCliente(LoginRequiredMixin, UpdateView):
    model = EmpresaCliente
    form_class = EmpresaClienteForm
    template_name = "empresa/update_empresa_cliente.html"
    success_url = reverse_lazy("empresa:list-empresa-cliente")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["PaisData"] = PaisEstadoCiudad.objects.all() 
        return context
        
    def form_valid(self, form):
        empresa = form.save()
        datapais = form.cleaned_data.get('paisestadociudad')
        empresa.paisestadociudad = PaisEstadoCiudad.objects.get(nombre = datapais)
        empresa.save()
        return super().form_valid(form)



"""  CRUD DE CONTACTOS DE LA EMPRESA CLIENTE  """

#Creacion de contacto y agragarlos a el empres cliente
class CreateContactoEmpresa(LoginRequiredMixin, CreateView):
    model = ContanctosEmpresa
    form_class = ContanctosEmpresaForm
    template_name = "empresa/create_contacto_empresa.html"
    success_url = reverse_lazy("empresa:list-empresa-cliente")

    def form_valid(self, form):
        contacto = form.save()
        empresa = EmpresaCliente.objects.get(id = self.kwargs['pk'])
        contacto.empresa = empresa
        contacto.save()
        empresa.contacto.add(contacto)
        empresa.save()
        return super().form_valid(form)

core/templates/empresa/create_contacto_empresa.html
{% extends 'core/base.html' %}
{% include 'core/nav.html' %}
{% block content %}
<div class="card shadow">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold">CREAR CONTACTO EMPRESA CLIENTE</p>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            <label class="text-dark text-center" for="nombre">Nombres</label>
            {{form.nombre.errors}}
        {{form.nombre}}
            <label class="textapellido-dark text-center" for="apellido">Apellidos</label>
            {{form.apellido.errors}}
        {{form.apellido}}
            <label class="text-dark text-center" for="email">Correo Electronico</label>
            {{form.email.errors}}
        {{form.email}}
            <label class="text-dark text-center" for="telefono">Telefono</label>
            {{form.telefono.errors}}
        {{form.telefono}}
            <label class="text-dark text-center" for="celular">Celular</label>
            {{form.celular.errors}}
        {{form.celular}}
            <button class="btn btn-primary btn-block text-white btn-user mt-5" type="submit">Crear Contacto</button>
        </form>
    </div>
</div>
{% endblock content %}
nombre

core/templates/empresa/delete_empresa.html
{% extends 'core/base.html' %}
{% include 'core/nav.html' %}
{% block content %}
<div class="card shadow">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold">ELIMINAR EMPRESA</p>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            <label class="text-dark text-center" for="nit">Seguro que quieres elimiar esta empresa?</label>
            <h4>{{ object.nombre }}</h4>
            <button class="btn btn-primary btn-block text-white btn-user mt-2" type="submit">Eliminar Empresa</button>
        </form>
    </div>
</div>
{% endblock content %}

core/templates/empresa/delete_empresa_cliente.html
{% extends 'core/base.html' %}
{% include 'core/nav.html' %}
{% block content %}
<div class="card shadow">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold">ELIMINAR EMPRESA CLIENTE</p>
    </div>
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            <label class="text-dark text-center" for="nit">Seguro que quieres elimiar esta empresa cliente?</label>
            <h4>{{ object.nombre }}</h4>
            <button class="btn btn-primary btn-block text-white btn-user mt-2" type="submit">Eliminar Empresa Cliente</button>
        </form>
    </div>
</div>
{% endblock content %}

core/templates/empresa/list_contacto_empresa.html
{% extends 'core/base.html' %}

{% block content %}
<div class="card shadow">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold upper">Contactos de {{ empresa.nombre }}</p>
    </div>
    <div class="card-body">
        <div
            class="table-responsive table mt-2"
            id="dataTable"
            role="grid"
            aria-describedby="dataTable_info"
        >
            <table class="table my-0" id="dataTable">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Celular</th>
                        <th>email</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <a href="{% url 'empresa:create-contacto-cliente' empresa.id %}" class="btn btn-primary text-white">Crear Contacto</a>
                <tbody>
                    {% for i in contacto  %}
                    <tr>
                        <td>{{i.nombre}}</td>
                        <td>{{i.apellido}}</td>
                        <td>{{i.celular}}</td>
                        <td>{{i.email}}</td>
                        <td><a href="{% url 'empresa:delete-contacto-cliente' i.id %}" class="btn btn-primary text-white">Eliminar </a>
                        <a href="{% url 'empresa:update-contacto-cliente' i.id %}" class="btn btn-primary text-white">Editar </a>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
                
            </table>
        </div>
        {% endblock content %}

core/templates/empresa/list_empresa.html
{% extends 'core/base.html' %}

{% block content %}
<div class="card shadow">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold">MIS EMPRESAS</p>
    </div>
    <div class="card-body">
        <div
            class="table-responsive table mt-2"
            id="dataTable"
            role="grid"
            aria-describedby="dataTable_info"
        >
            <table class="table my-0" id="dataTable">
                <thead>
                    <tr>
                        <th>Nit</th>
                        <th>Nombre</th>
                        <th>Usuario Pertenecen a la empresa</th>
                        <th>Telefono</th>
                        <th>Email</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in object %}
                    <tr>
                        <td>{{i.nit}}</td>
                        <td>{{i.nombre}}</td>
                        
                        <td>
                        {% if i.usuarios.all  %}
                        {% for usuario in i.usuarios.all  %}
                        <a class="btn-block text-dark" style="text-decoration:None" href="{% url 'empresa:delete-usuario-invitado' usuario %}">{{usuario}} Eliminar?</a>
                        {% endfor %}
                        {% else %}
                        Ningun usuario pertenece a esta empresa
                        {% endif %}
                        </td>
                        <td>{{i.telefono}}</td>
                        <td>{{i.email}}</td>
                        <td><a href="{% url 'empresa:delete-empresa' i.id %}" class="btn btn-primary text-white">Eliminar </a>
                        <a href="{% url 'empresa:update-empresa' i.id %}" class="btn btn-primary text-white">Editar </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endblock content %}

core/templates/empresa/list_empresa_cliente.html
{% extends 'core/base.html' %}

{% block content %}
<div class="card shadow">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold">EMPRESAS CLIENTE</p>
    </div>
    <div class="card-body">
        <div
            class="table-responsive table mt-2"
            id="dataTable"
            role="grid"
            aria-describedby="dataTable_info"
        >
            <table class="table my-0" id="dataTable">
                <thead>
                    <tr>
                        <th>Nit</th>
                        <th>Nombre</th>
                        <th>Usuario Pertenecen a la empresa</th>
                        <th>Telefono</th>
                        <th>Agregar Contacto</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for i in object_list  %}
                    <tr>
                        <td>{{i.nit}}</td>
                        <td>{{i.nombre}}</td>
                        
                        <td>
                        {% if i.contacto.all %}
                        {% for usuario in i.contacto.all %}
                        
                        <a class="btn-block text-dark" style="text-decoration:None">{{usuario.nombre}}</a>
                        {% endfor %}
                        {% else %}
                        No tienes contactos en esta empresa
                        {% endif %}
                        </td>
                        <td>{{i.telefono}}</td>
                        <td><a href="{% url 'empresa:list-contacto-cliente' i.id %}" class="btn btn-primary text-white">Ver o Crear Contactos </a></td>
                        <td><a href="{% url 'empresa:delete-empresa-cliente' i.id %}" class="btn btn-primary text-white">Eliminar </a>
                        <a href="{% url 'empresa:update-empresa-cliente' i.id %}" class="btn btn-primary text-white">Editar </a>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endblock content %}

core/templates/empresa/list_invitaciones.html
{% extends 'core/base.html' %}

{% block content %}
<div class="card shadow">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold">MIS INVITACIONES</p>
    </div>
    <div class="card-body">
        <div
            class="table-responsive table mt-2"
            id="dataTable"
            role="grid"
            aria-describedby="dataTable_info">
            <table class="table my-0" id="dataTable">
                <thead>
                    <tr>
                        <th>Empresa</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in invitaciones  %}
                    {% comment %} Se valida si la invitacion tiene empresa {% endcomment %}
                    {% if i.empresa %}
                    <tr>
                        <td>{{i.empresa}}</td>
                        {% if i.estado == 'Espera' %}
                        <td>
                        <a href="{% url 'empresa:aceptar-invitaciones' i.user %}" class="btn btn-primary text-white"> Aceptar</a>
                        <a href="{% url 'empresa:rechazar-invitaciones' i.user %}" class="btn btn-primary text-white"> Rechazar</a>
                        </td>
                        {% else %}
                        <td>
                        <a href="" class="btn btn-primary text-white"> {{i.estado}}</a>
                        </td>
                        {% endif %}

                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endblock content %}

core/templates/empresa/list_usuarios.html
{% extends 'core/base.html' %}

{% block content %}
<div class="card shadow">
    <div class="card-header py-3">
        <p class="text-primary m-0 font-weight-bold">Enviar Invitaciones</p>
    </div>
    <div class="card-body">
        <div
            class="table-responsive table mt-2"
            id="dataTable"
            role="grid"
            aria-describedby="dataTable_info">
            <table class="table my-0" id="dataTable">
                <thead>
                    <tr>
                        <th>Usuario</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in object_list  %}
                    {% comment %} El usuario que esta logeado no se puede mandar una invitacion asi mismo {% endcomment %}
                    {% if i.user != user %}
                    {% if not i.empresa %}
                    <tr>
                        <td>{{i.user}}</td>

                        <td>
                        {% comment %} Validacion del estado de la inivtacion {% endcomment %}
                        {% if i.estado == 'Espera' %}
                        {% comment %} si la invitacion tiene la misma empresa permitir mostrar el estado que tiene
                        con esa empresa si no mostra la posibilidad de invitar {% endcomment %}
                            {% if i.empresa == empresa and empresa !=  None %}
                                <a href="" class="btn btn-primary text-white">{{i.estado}}</a>
                            {% else %}
                            {% if empresa %}
                                <a href="{% url 'empresa:invitar-usuario' i.user %}" class="btn btn-primary text-white">Invitar</a>
                            {% else %}
                            {% comment %} No se puede invitar a una persona a la empresa si no tiene empresa {% endcomment %}
                                <a href="" class="btn btn-primary text-white">No tienes empresa</a>
                            {% endif %}
                        {% endif %}
                        {% else %}
                        {% if i.estado == 'Aceptada' %}
                        {% if i.empresa == empresa %}
                        <a href="" class="btn btn-primary text-white">{{i.estado}}</a>
                        {% else %}
                        <a href="{% url 'empresa:invitar-usuario' i.user %}" class="btn btn-primary text-white">Invitar</a>
                        {% endif %}
                        {% else %}
                        <a href="{% url 'empresa:invitar-usuario' i.user %}" class="btn btn-primary text-white">Invitar</a>
                        {% endif %}
                    {% endif %}
                        </td>
                    </tr>

                    {% endif %}
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endblock content %}